
version: 2

models:
    - name: transaction_detail
      description: "地块成交明细表"
      columns:
          - name: land_uid
            description: "清洗后的唯一地块编号，只包含字母和数字"
            tests:
                - unique
                - not_null